#!/usr/bin/env bash
# Hermes entrypoint for OpenShell — works in BOTH supervisor modes:
#
#   combined (default)  OpenShell --mode network,process execs this under
#                       Landlock + uid drop (process leaf MainPID).
#   network             sandbox-workload.service nsenter's the sandbox netns,
#                       setpriv-drops, then execs this (no Landlock).
#
# Foreground-only: `exec hermes gateway run` so a gateway crash fails this
# process and the parent restarts it —
#   combined → openshell-sandbox.service Restart=on-failure
#   network  → sandbox-workload.service Restart=on-failure
#
# Dashboard is a separate system unit (hermes-dashboard.service) that joins
# the sandbox netns; systemd owns its Restart= policy. Do not background
# workloads here — the parent never sees child exits.
#
# Host UX after Ready:
#   openshell forward service <name> --target-port 9119 --local 9119
set -euo pipefail

export HOME="${HOME:-/sandbox}"
export HERMES_HOME="${HERMES_HOME:-/sandbox/.hermes}"
export HERMES_TUI_DIR="${HERMES_TUI_DIR:-/opt/hermes/ui-tui}"
export PATH="/opt/hermes/.venv/bin:/usr/local/bin:/usr/bin:/bin:${PATH:-}"
# Landlock: /dev/ptmx denied; sitecustomize routes openpty → /dev/pts/ptmx.
export PYTHONPATH="/usr/local/lib/hermes/pythonpath${PYTHONPATH:+:${PYTHONPATH}}"
export USER="${USER:-sandbox}"
export LOGNAME="${LOGNAME:-sandbox}"
export NODE_USE_ENV_PROXY="${NODE_USE_ENV_PROXY:-1}"

if [ -f /run/openshell/provider.env ]; then
  set -a
  # shellcheck disable=SC1091
  . /run/openshell/provider.env
  set +a
fi
if [ -r /etc/sandbox/env ]; then
  set -a
  # shellcheck disable=SC1091
  . /etc/sandbox/env
  set +a
fi

RUNTIME_DIR="${HERMES_HOME}/runtime"
mkdir -p "$RUNTIME_DIR"
chmod 700 "$RUNTIME_DIR"
{
  echo "# generated by hermes-start.sh — do not edit"
  env | awk -F= '
    $1 ~ /^(HTTP_PROXY|HTTPS_PROXY|ALL_PROXY|http_proxy|https_proxy|all_proxy|NO_PROXY|no_proxy|grpc_proxy|SSL_CERT_FILE|REQUESTS_CA_BUNDLE|CURL_CA_BUNDLE|GIT_SSL_CAINFO|NODE_EXTRA_CA_CERTS|NODE_USE_ENV_PROXY|DENO_CERT|NEMOCLAW_|OPENSHELL_|HERMES_|ANTHROPIC_|GOOGLE_|GCP_|VERTEX_|CLOUD_ML_|GOOSE_|SIGNAL_|SLACK_|GITHUB_|GITLAB_|ATLASSIAN_|JIRA_|GWS_|SUPERVISOR_MODE)/ {
      key=$1
      val=substr($0, index($0, "=") + 1)
      gsub(/\\/, "\\\\", val)
      gsub(/"/, "\\\"", val)
      printf "%s=\"%s\"\n", key, val
    }'
  printf 'HOME="%s"\n' "${HOME}"
  printf 'HERMES_HOME="%s"\n' "${HERMES_HOME}"
  printf 'HERMES_TUI_DIR="%s"\n' "${HERMES_TUI_DIR}"
  printf 'PATH="%s"\n' "${PATH}"
  printf 'PYTHONPATH="%s"\n' "${PYTHONPATH}"
  printf 'USER="%s"\n' "${USER}"
  printf 'LOGNAME="%s"\n' "${LOGNAME}"
} >"${RUNTIME_DIR}/workload.env"
chmod 600 "${RUNTIME_DIR}/workload.env"

cd "$HOME"
# Replace this process — gateway exit status propagates to OpenShell / systemd.
exec /opt/hermes/.venv/bin/hermes gateway run
