#!/usr/bin/env bash
# Hermes entrypoint for OpenShell — works in BOTH supervisor modes:
#
#   combined (default)  OpenShell --mode network,process execs this under
#                       Landlock + uid drop. We stay in that process tree.
#   network             sandbox-workload.service nsenter's the sandbox netns,
#                       setpriv-drops, then execs this (no Landlock).
#
# In both cases this script is PID 1 of the Hermes tree: it forks
# `hermes gateway` + `hermes dashboard`, inherits/sources proxy+TLS env, and
# restarts children. Do NOT nest `systemd --user` here — under combined mode
# Landlock that fails (no cgroup delegation). Linger user@UID on the guest
# root netns is the wrong network namespace for these workloads.
#
# Host UX after Ready:
#   openshell forward service <name> --target-port 9119 --local 9119
set -euo pipefail

export HOME="${HOME:-/sandbox}"
export HERMES_HOME="${HERMES_HOME:-/sandbox/.hermes}"
export HERMES_TUI_DIR="${HERMES_TUI_DIR:-/opt/hermes/ui-tui}"
export PATH="/opt/hermes/.venv/bin:/usr/local/bin:/usr/bin:/bin:${PATH:-}"
# Landlock: /dev/ptmx denied; sitecustomize routes openpty → /dev/pts/ptmx.
export PYTHONPATH="/usr/local/lib/hermes/pythonpath${PYTHONPATH:+:${PYTHONPATH}}"
export USER="${USER:-sandbox}"
export LOGNAME="${LOGNAME:-sandbox}"
# Node fetch / undici honor HTTP(S)_PROXY when set.
export NODE_USE_ENV_PROXY="${NODE_USE_ENV_PROXY:-1}"

if [ -f /run/openshell/provider.env ]; then
  set -a
  # shellcheck disable=SC1091
  . /run/openshell/provider.env
  set +a
fi
# /etc/sandbox/env is often root-only (virtio secret); skip if unreadable.
if [ -r /etc/sandbox/env ]; then
  set -a
  # shellcheck disable=SC1091
  . /etc/sandbox/env
  set +a
fi

RUNTIME_DIR="${HERMES_HOME}/runtime"
mkdir -p "$RUNTIME_DIR"
chmod 700 "$RUNTIME_DIR"

# Snapshot for debugging (combined: OpenShell-injected env; network: workload-run).
{
  echo "# generated by hermes-start.sh — do not edit"
  env | awk -F= '
    $1 ~ /^(HTTP_PROXY|HTTPS_PROXY|ALL_PROXY|http_proxy|https_proxy|all_proxy|NO_PROXY|no_proxy|grpc_proxy|SSL_CERT_FILE|REQUESTS_CA_BUNDLE|CURL_CA_BUNDLE|GIT_SSL_CAINFO|NODE_EXTRA_CA_CERTS|NODE_USE_ENV_PROXY|DENO_CERT|NEMOCLAW_|OPENSHELL_|HERMES_|ANTHROPIC_|GOOGLE_|GCP_|VERTEX_|CLOUD_ML_|GOOSE_|SIGNAL_|SLACK_|GITHUB_|GITLAB_|ATLASSIAN_|JIRA_|GWS_|SUPERVISOR_MODE)/ {
      key=$1
      val=substr($0, index($0, "=") + 1)
      gsub(/\\/, "\\\\", val)
      gsub(/"/, "\\\"", val)
      printf "%s=\"%s\"\n", key, val
    }'
  printf 'HOME="%s"\n' "${HOME}"
  printf 'HERMES_HOME="%s"\n' "${HERMES_HOME}"
  printf 'HERMES_TUI_DIR="%s"\n' "${HERMES_TUI_DIR}"
  printf 'PATH="%s"\n' "${PATH}"
  printf 'PYTHONPATH="%s"\n' "${PYTHONPATH}"
  printf 'USER="%s"\n' "${USER}"
  printf 'LOGNAME="%s"\n' "${LOGNAME}"
} >"${RUNTIME_DIR}/workload.env"
chmod 600 "${RUNTIME_DIR}/workload.env"

cd "$HOME"

GATEWAY_PID=""
DASHBOARD_PID=""

cleanup() {
  local pid
  for pid in "${GATEWAY_PID:-}" "${DASHBOARD_PID:-}"; do
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
    fi
  done
  wait 2>/dev/null || true
}
trap cleanup EXIT INT TERM

start_gateway() {
  /opt/hermes/.venv/bin/hermes gateway run \
    >>"${RUNTIME_DIR}/gateway.log" 2>&1 &
  GATEWAY_PID=$!
  echo "$GATEWAY_PID" >"${RUNTIME_DIR}/gateway.pid"
  echo "hermes-start: gateway pid=${GATEWAY_PID}" >&2
}

start_dashboard() {
  /opt/hermes/.venv/bin/hermes dashboard \
    --host 127.0.0.1 --port 9119 --no-open \
    >>"${RUNTIME_DIR}/dashboard.log" 2>&1 &
  DASHBOARD_PID=$!
  echo "$DASHBOARD_PID" >"${RUNTIME_DIR}/dashboard.pid"
  echo "hermes-start: dashboard pid=${DASHBOARD_PID}" >&2
}

start_gateway
start_dashboard

# Stay alive as the OpenShell / sandbox-workload entrypoint; restart children.
while true; do
  if [ -n "${GATEWAY_PID}" ] && ! kill -0 "${GATEWAY_PID}" 2>/dev/null; then
    echo "hermes-start: gateway exited; restarting" >&2
    start_gateway
  fi
  if [ -n "${DASHBOARD_PID}" ] && ! kill -0 "${DASHBOARD_PID}" 2>/dev/null; then
    echo "hermes-start: dashboard exited; restarting" >&2
    start_dashboard
  fi
  sleep 2
done
