#!/usr/bin/env bash
# Hermes entrypoint for OpenShell (combined or network-only sibling).
#
# Runs a nested `systemd --user` *inside the OpenShell sandbox netns* so
# hermes-gateway + hermes-dashboard are proper user units but still inherit
# the sandbox network / Landlock tree. The linger user@UID on the guest
# root netns is intentionally separate (podman cgroup manager only).
#
# Host UX after boot: port-forward the dashboard only:
#   openshell forward service <name> --target-port 9119 --local 9119
set -euo pipefail

export HOME="${HOME:-/sandbox}"
export HERMES_HOME="${HERMES_HOME:-/sandbox/.hermes}"
export HERMES_TUI_DIR="${HERMES_TUI_DIR:-/opt/hermes/ui-tui}"
export PATH="/opt/hermes/.venv/bin:/usr/local/bin:/usr/bin:/bin:${PATH:-}"
# Landlock: /dev/ptmx denied; sitecustomize routes openpty → /dev/pts/ptmx.
export PYTHONPATH="/usr/local/lib/hermes/pythonpath${PYTHONPATH:+:${PYTHONPATH}}"

if [ -f /run/openshell/provider.env ]; then
  set -a
  # shellcheck disable=SC1091
  . /run/openshell/provider.env
  set +a
fi
# /etc/sandbox/env is often root-only (virtio secret); skip if unreadable.
if [ -r /etc/sandbox/env ]; then
  set -a
  # shellcheck disable=SC1091
  . /etc/sandbox/env
  set +a
fi

RUNTIME_DIR="${HERMES_HOME}/user-systemd"
mkdir -p "$RUNTIME_DIR"
chmod 700 "$RUNTIME_DIR"
# Separate from linger user@UID (guest root netns / podman). This manager
# lives in the OpenShell sandbox netns with the gateway + dashboard.
export XDG_RUNTIME_DIR="$RUNTIME_DIR"
export DBUS_SESSION_BUS_ADDRESS="unix:path=${RUNTIME_DIR}/bus"

# Snapshot proxy / TLS / provider env for the user units (they do not inherit
# a login session). Rewrite on every start so OpenShell refreshes apply.
# Values are double-quoted systemd EnvironmentFile entries.
{
  echo "# generated by hermes-start.sh — do not edit"
  env | awk -F= '
    $1 ~ /^(HTTP_PROXY|HTTPS_PROXY|ALL_PROXY|http_proxy|https_proxy|all_proxy|NO_PROXY|no_proxy|grpc_proxy|SSL_CERT_FILE|REQUESTS_CA_BUNDLE|CURL_CA_BUNDLE|GIT_SSL_CAINFO|NODE_EXTRA_CA_CERTS|NODE_USE_ENV_PROXY|DENO_CERT|NEMOCLAW_|OPENSHELL_|HERMES_|ANTHROPIC_|GOOGLE_|GCP_|VERTEX_|CLOUD_ML_|GOOSE_|SIGNAL_|SLACK_|GITHUB_|GITLAB_|ATLASSIAN_|JIRA_|GWS_)/ {
      key=$1
      val=substr($0, index($0, "=") + 1)
      gsub(/\\/, "\\\\", val)
      gsub(/"/, "\\\"", val)
      printf "%s=\"%s\"\n", key, val
    }'
  printf 'HOME="%s"\n' "${HOME}"
  printf 'HERMES_HOME="%s"\n' "${HERMES_HOME}"
  printf 'HERMES_TUI_DIR="%s"\n' "${HERMES_TUI_DIR}"
  printf 'PATH="%s"\n' "${PATH}"
  printf 'PYTHONPATH="%s"\n' "${PYTHONPATH}"
  printf 'USER="%s"\n' "${USER:-sandbox}"
  printf 'LOGNAME="%s"\n' "${LOGNAME:-sandbox}"
} >"${RUNTIME_DIR}/workload.env"
chmod 600 "${RUNTIME_DIR}/workload.env"

cd "$HOME"

# Stop a prior nested manager if this entrypoint is restarted in-place.
if [ -S "${RUNTIME_DIR}/bus" ]; then
  systemctl --user exit 2>/dev/null || true
  # Give the old manager a moment to release the bus socket.
  for _ in 1 2 3 4 5; do
    [ -S "${RUNTIME_DIR}/bus" ] || break
    sleep 0.2
  done
  rm -f "${RUNTIME_DIR}/bus" "${RUNTIME_DIR}/bus.lock" 2>/dev/null || true
fi

# Replace this process with a user systemd whose default unit is hermes.target.
# Children (gateway + dashboard) stay in this netns / cgroup under OpenShell.
exec /usr/lib/systemd/systemd --user --unit=hermes.target
